[package]
org = "ballerina"
name = "ai.np"
version = "0.5.0"
authors = ["Ballerina"]
keywords = ["natural programming", "ai"]
repository = "https://github.com/ballerina-platform/module-ballerina-ai.np"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true

