[plugin]
id = "ai.np-compiler-plugin"
class = "io.ballerina.lib.ai.np.compilerplugin.CompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai.np-compiler-plugin-0.4.3-SNAPSHOT.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-2.3.0.jar"

